<a href="https://colab.research.google.com/github/lakshya-raj/mlzoomcamp/blob/main/MLZoomcampWeek1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

**Question 1:** Version of Pandas:

In [5]:
pd.__version__

'1.5.3'

In [6]:
%%shell

wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-18 19:03:00--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  --.-KB/s    in 0.07s   

2023-09-18 19:03:00 (20.3 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [7]:
df = pd.read_csv('/content/housing.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


**Question 2:**  Number of columns in the dataset*

In [8]:
df.shape[-1]

10

**Question 3**: Select columns with missing data


In [9]:
df.columns[df.isna().any()]

Index(['total_bedrooms'], dtype='object')

**Question 4:** Number of unique values in the 'ocean_proximity' column

In [10]:
df.ocean_proximity.value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

**Question 5:** Average value of the 'median_house_value' for the houses near the bay

In [11]:
df[df.ocean_proximity == 'NEAR BAY'].median_house_value.mean()

259212.31179039303

In [12]:
df.total_bedrooms.value_counts()

280.0     55
331.0     51
345.0     50
343.0     49
393.0     49
          ..
2961.0     1
1915.0     1
1215.0     1
3298.0     1
1052.0     1
Name: total_bedrooms, Length: 1923, dtype: int64

In [14]:
df.total_bedrooms.describe()

count    20433.000000
mean       537.870553
std        421.385070
min          1.000000
25%        296.000000
50%        435.000000
75%        647.000000
max       6445.000000
Name: total_bedrooms, dtype: float64

In [17]:
?df.fillna

In [18]:
df2 = df.copy()

In [19]:
mean_bedroom = df2.total_bedrooms.mean()

In [20]:
mean_bedroom

537.8705525375618

In [22]:
df2.total_bedrooms.fillna(mean_bedroom)
df2.total_bedrooms.describe()

count    20433.000000
mean       537.870553
std        421.385070
min          1.000000
25%        296.000000
50%        435.000000
75%        647.000000
max       6445.000000
Name: total_bedrooms, dtype: float64

Question 6: Has the mean value changed after filling missing values?


In [24]:
df2.total_bedrooms.mean() - mean_bedroom

0.0

In [25]:
df3 = df[df.ocean_proximity == 'ISLAND']
df3.head

<bound method NDFrame.head of       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317  

In [28]:
df4 = df3[['housing_median_age', 'total_rooms', 'total_bedrooms']]
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 8314 to 8318
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   housing_median_age  5 non-null      float64
 1   total_rooms         5 non-null      float64
 2   total_bedrooms      5 non-null      float64
dtypes: float64(3)
memory usage: 160.0 bytes


In [30]:
X = df4.to_numpy()
type(X)

numpy.ndarray

In [31]:
M = X.T @ X
M

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [33]:
M_inv = np.linalg.inv(M)
M_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [36]:
y = np.array([950, 1300, 800, 1000, 1300])
type(y)

numpy.ndarray

In [37]:
w = M_inv @ X.T @ y
w

array([23.12330961, -1.48124183,  5.69922946])

**Questions 7**: Value of the last element of w

In [38]:
w[-1]

5.699229455065586